import './jquery.vpage.init.js';
import './jquery.vpage.existModel.js';
import './jquery.vpage.historyPush.js';
import './jquery.vpage.getMixParams.js';
import './jquery.vpage.getUrlParams.js';
import './jquery.vpage.destroy.js';
import './jquery.vpage.callModel.js';
import './jquery.vpage.model.js';
import './jquery.vpage.helper.js';